on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.20-alpine
    steps:
      - uses: actions/checkout@v2
      - run: go mod vendor
      - run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o app.exe
      - run: mkdir -p dist
      - run: mv app.exe dist/
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: v.0.1.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/octet-stream